START_COMMAND = '/control/start/';
PARK_COMMAND = '/control/park/duration/timer';
PAUSE_COMMAND = '/control/pause';
CHARGING = 'CHARGING';
MOWING = 'MOWING';
LEAVING = 'LEAVING';
PARKED = 'PARKED_IN_CS';
STOPPED_IN_GARDEN = 'STOPPED_IN_GARDEN';

IN_OPERATION = 'IN_OPERATION';
RESTRICTED = 'RESTRICTED';

module.exports = {
  START_COMMAND,
  PAUSE_COMMAND,
  PARK_COMMAND,
  CHARGING,
  IN_OPERATION,
  MOWING,
  LEAVING,
  PARKED,
  STOPPED_IN_GARDEN,
};
