START_COMMAND = '/control/start/';
PARK_COMMAND = '/control/park/duration/timer';
PAUSE_COMMAND = '/control/pause';
CHARGING = 'CHARGING';
MOWING = 'MOWING';
LEAVING = 'LEAVING';
PAKED = 'PARKED_IN_CS';

IN_OPERATION = 'IN_OPERATION';
RESTRICTED = 'RESTRICTED';

module.exports = {
  START_COMMAND,
  PAUSE_COMMAND,
  PARK_COMMAND,
  CHARGING,
  IN_OPERATION,
  MOWING,
};

//"activity"
//"CHARGING"
//"LEAVING"
//'MOWING';
//"PARKED_IN_CS"
//"GOING_HOME"

//restrictedReason
//"NOT_APPLICABLE"
//"PARK_OVERRIDE"

//state
//"IN_OPERATION"
//"RESTRICTED"
